name: Labour Web CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/labour/web/**'
      - '.github/workflows/**'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'apps/labour/web/**'
      - '.github/workflows/**'

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./apps/labour/web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: './apps/labour/web/.nvmrc'
          cache: 'npm'
          cache-dependency-path: ./apps/labour/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run typecheck
        run: npm run typecheck

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
        env:
          VITE_LABOUR_SERVICE_URL: ${{ vars.LABOUR_WORKER_URL }}
          VITE_LABOUR_SERVICE_WEBSOCKET: ${{ vars.LABOUR_WORKER_WEBSOCKET }}
          VITE_CONTACT_SERVICE_URL: ${{ vars.CONTACT_WORKER_URL }}
          VITE_POST_LOGOUT_REDIRECT: ${{ vars.MARKETING_URL }}
          VITE_CLOUDFLARE_SITEKEY: ${{ vars.CLOUDFLARE_SITEKEY }}
          VITE_CLERK_PUBLISHABLE_KEY: ${{ vars.LABOUR_APP_CLERK_PUBLIC_KEY }}

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: labour-web-build-${{ github.sha }}
          path: ./apps/labour/web/dist/
          retention-days: 7
